name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore Packages
      run: nuget restore GithubActionsDemo.sln

    #- name: Build Solution
    #  run: |
    #    msbuild.exe GithubActionsDemo.sln -t:rebuild -p:Configuration=Release -p:platform="x64"

    - name: Make tmp dir
      run: mkdir /tmp

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: /tmp

  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      
      - name: Upload to mega
        uses: Difegue/action-megacmd@master
        with:
          args: put tmp Test
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}