name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore Packages
      run: nuget restore GithubActionsDemo.sln

    - name: Build Solution
      run: |
        msbuild.exe GithubActionsDemo.sln -t:rebuild -p:Configuration=Release -p:platform="x64" -p:OutDir=C:\Output
    
    - name: Zip build output 
      run: tar.exe -cf C:\Output.zip C:\Output


    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: C:\Output.zip

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      
      - name: Upload to mega
        uses: Difegue/action-megacmd@master
        with:
          args: put Output.zip Test
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}