name: Upload

on:
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Create directory
        run: mkdir tmp 
      
      - name: Upload to mega
        uses: Difegue/action-megacmd@master
        with:
          args: put tmp Test
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}